version: '3'

services:
  db:
    image: ${POSTGRES_IMAGE}:${POSTGRES_VERSION}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  omero:
    build:
      context: ./omeroserver
      args:
        - OMEROSERVER_BASE_IMAGE=${OMERO_SERVER_IMAGE}:${OMERO_SERVER_VERSION}
    environment:
      - ROOTPASS=${ROOTPASS}
      - CONFIG_omero_db_host=db
      - CONFIG_omero_db_user=postgres
      - CONFIG_omero_db_name=postgres
      - CONFIG_omero_db_pass=${POSTGRES_PASSWORD}
      - CONFIG_omero_upgrades_url=
      - CONFIG_omero_policy_binary__access=${OMERO_POLICY_BINARY_ACCESS}
      - CONFIG_Ice_IPv6=0
    ports:
      - "4063:4063"
      - "4064:4064"
  web:
    build:
      context: ./omeroweb
      args:
        - OMEROWEB_BASE_IMAGE=${OMERO_WEB_IMAGE}:${OMERO_WEB_VERSION}
    environment:
      - CONFIG_omero_upgrades_url=
      - CONFIG_Ice_IPv6=0
    ports:
      - "${OMERO_WEB_PORT}:4080"
  micromamba:
    build:
      context: ./micromamba
  ontop:
    build:
      context: ./ontop
    environment:
      - ONTOP_DB_HOST=db
      - ONTOP_DB_USER=postgres
      - ONTOP_DB_NAME=postgres
      - ONTOP_DB_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 5s
      retries: 3
    command: >
      /bin/sh -c "
      pytest"
