# Builds using docker
---
name: Build

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    strategy:
      matrix:
        python: [3.9]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Add variable
        run: |
          run: |
            echo "COMPOSE_FILE=docker-compose.yml:volumes.yml" >> $GITHUB_PATH
      - name: Set up
        run: |
          mkdir /tmp/omero-app
          cp -r . /tmp/omero-app/.omero
      - name: Build
        run: |
          cd /tmp/omero-app
          .omero/compose up -d
      - name: Install Micromamba
        run: |
          curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj -C /usr/local/bin/ --strip-components=1 bin/micromamba
          micromamba shell init -s bash -p ~/micromamba
          source ~/.bashrc
          micromamba create -y -n test_env -c conda-forge python=3.9 omero-py rdflib requests pytest
          micromamba activate test_env
          echo "omero-py, rdflib, pytest, and requests installed successfully"
      - name: Test
        run: |
          chmod +x ontop-test/test_infra_ontop/entrypoint.sh  ontop-test/test_infra_ontop/test_endpoint.py  ontop-test/test_infra_ontop/insert_data.sh
          bash ontop-test/test_infra_ontop/entrypoint.sh
      - name: Tear down
        run: |
          .omero/compose down
          .omero/persist.sh backup
          .omero/persist.sh --restore backup
      - name: Check health status and logs on failure
        if: failure()
        run: |
          docker ps -a
          docker inspect omeroapp-omero-1
          docker logs omeroapp-omero-1
